language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
script:
  - dotnet test ./tests/FluidHttp.Tests
  
