language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
jobs:
  include:
    - stage: build
      script: 
        - cd ./src/FluidHttp
        - dotnet restore
        - dotnet build
    - stage: test
      script:
        - cd ./tests/FluidHttp.Tests
        - dotnet restore
        - dotnet test